# Todo:Improve the terminal colors!!
# Font, my favorite is jetbrains :)

font_family Terminus 
#Fuck the "are you sure you wanna close it?" confirmation
confirm_os_window_close 0
# Make the cursor shape a beam
shell_integration no-cursor
cursor_shape beam
cursor_trail 4
# Padding
window_padding_width 7
window_padding_height 10

# Scroll back up to 3000 lines.
scrollback_lines 3000

#Default font size.
font_size 12

#Shell, we are gonna use fish
shell fish
# Just a keybind to change font size to your liking, it's CTRL + scroll wheel up or down.
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Background opacity, set to 0 if you want blur/transparency.
# Blur works with hyprland, or sway-fx as a drop-in replacement for sway.
background_opacity 0.8


# Finally, the COLORS! these use the design system I made for this rice.
cursor               #44EEFF

selection_background #d8cab8
selection_foreground #141216

background           #000000
foreground           #FFFFFF

color0               #000088
color8               #44CCFF 
color1               #000088
color9               #fc4649
color2               #FFFFFF
color10              #6361A0
color3               #AC82E9
color11              #000088
color4               #000088
color12              #7b91fc
color5               #f3fc7b
color13              #000088
color6               #000088
color14              #000088
color7               #000088
color15              #000088
